name: OpenBuild Acro 1510
board: FluidNC 4X 2209 V3

stepping:
  engine: RMT
  idle_ms: 0
  pulse_us: 10
  dir_delay_us: 1
  disable_delay_us: 0
  segments: 12

uart1:
  baud: 115200
  mode: 8N1
  txd_pin: gpio.17
  rxd_pin: gpio.16

i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.27

sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5
  frequency_hz: 8000000

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

control:
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

axes:
  shared_stepper_disable_pin: NO_PIN
  homing_runs: 2

  x:
    steps_per_mm: 57.300
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 1270.000
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 25.000
      seek_mm_per_min: 5000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      hard_limits: true
      pulloff_mm: 1.000
      limit_neg_pin: NO_PIN
      limit_pos_pin: i2so.0
      limit_all_pin: NO_PIN
      tmc_2209:
        addr: 0
        uart_num: 1
        step_pin: i2so.1
        direction_pin: i2so.2
        r_sense_ohms: 0.110
        run_amps: 1.000
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: 0
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false

  y:
    steps_per_mm: 57.143
    max_rate_mm_per_min: 5000.000
    acceleration_mm_per_sec2: 100.000
    max_travel_mm: 810.000
    soft_limits: false
    homing:
      cycle: 1
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 25.000
      seek_mm_per_min: 5000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      hard_limits: true
      pulloff_mm: 1.000
      limit_neg_pin: NO_PIN
      limit_pos_pin: i2so.3
      limit_all_pin: NO_PIN
      tmc_2209:
        addr: 1
        uart_num: 1
        step_pin: i2so.4
        direction_pin: i2so.5
        r_sense_ohms: 0.110
        run_amps: 1.000
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: 0
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false

    motor1:
      hard_limits: true
      pulloff_mm: 1.000
      limit_neg_pin: NO_PIN
      limit_pos_pin: i2so.3
      limit_all_pin: NO_PIN
      tmc_2209:
        addr: 2
        uart_num: 1
        step_pin: i2so.6
        direction_pin: i2so.7
        r_sense_ohms: 0.110
        run_amps: 1.000
        hold_amps: 0.500
        microsteps: 16
        stallguard: 0
        stallguard_debug: 0
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false

  z:
    steps_per_mm: 500.000
    max_rate_mm_per_min: 500.000
    acceleration_mm_per_sec2: 10.000
    max_travel_mm: 200.000
    soft_limits: false
    homing:
      cycle: 2
      allow_single_axis: true
      positive_direction: true
      mpos_mm: 200.000
      feed_mm_per_min: 25.000
      seek_mm_per_min: 5000.000
      settle_ms: 250
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      hard_limits: true
      pulloff_mm: 1.000
      limit_neg_pin: NO_PIN
      limit_pos_pin: i2so.8
      limit_all_pin: NO_PIN
      tmc_2209:
        addr: 3
        uart_num: 1
        step_pin: i2so.9
        direction_pin: i2so.10
        r_sense_ohms: 0.110
        run_amps: 0.400
        hold_amps: 0.200
        microsteps: 16
        stallguard: 0
        stallguard_debug: 0
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: false

coolant:
  flood_pin: NO_PIN
  mist_pin: NO_PIN
  delay_ms: 0

probe:
  pin: gpio.25:pu
  check_mode_start: true
  hard_stop: false
  probe_hard_limit: false

macros:
  n0:
  n1:
  n2:
  n3:
  startup_line0:
  startup_line1:
  after_homing:
  after_reset:
  after_unlock:

start:
  must_home: false
  deactivate_parking: true
  check_limits: true

parking:
  enable: false
  axis: Z
  target_mpos_mm: -5.000
  rate_mm_per_min: 800.000
  pullout_distance_mm: 5.000
  pullout_rate_mm_per_min: 250.000

user_outputs:
  analog0_hz: 5000
  analog0_pin: NO_PIN
  analog1_hz: 5000
  analog1_pin: NO_PIN
  analog2_hz: 5000
  analog2_pin: NO_PIN
  analog3_hz: 5000
  analog3_pin: NO_PIN
  digital0_pin: NO_PIN
  digital1_pin: NO_PIN
  digital2_pin: NO_PIN
  digital3_pin: NO_PIN

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: true
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 16
