name: TMC2209 XYYZ PWM
board: FluidNC 4X 2209
stepping:
  engine: I2S_STREAM
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 4
  disable_delay_us: 0
uart1:
  txd_pin: gpio.26
  rxd_pin: gpio.2
  baud: 115200
  mode: 8N1
axes:
  shared_stepper_disable_pin: NO_PIN
  z:
    steps_per_mm: 395.8
    max_rate_mm_per_min: 1000
    acceleration_mm_per_sec2: 40
    max_travel_mm: 200
    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      pulloff_mm: 10
      tmc_2209:
        uart_num: 1
        addr: 2
        r_sense_ohms: 0.11
        run_amps: 1.2
        hold_amps: 0.5
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: CoolStep
        homing_mode: CoolStep
        use_enable: true
        direction_pin: i2so.9
        step_pin: i2so.10
        disable_pin: i2so.8
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17
sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN
coolant:
  flood_pin: NO_PIN
  mist_pin: gpio.27
  delay_ms: 0
pwm:
  pwm_hz: 5000
  direction_pin: NO_PIN
  output_pin: gpio.25
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  spinup_ms: 0
  spindown_ms: 0
  tool_num: 0
  speed_map: 0=0.000% 10000=100.000%
  off_on_alarm: false
start:
  must_home: false
